apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        # - image: quay.io/jesse_antoszyk/nginx:latest
        # - image: codefreshjesse/express-microservice2:ba63f092d0aebc502e66aef41ac56bf47b751844
        # d3cb357 03a3fc0 99d94a2
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: express
          ports:
            - containerPort: 3000
  minReadySeconds: 30
  strategy:
    canary:
      analysis:
        templates:
        - templateName: pass-always
        - templateName: mixed-tests
        startingStep: 1
      steps:
        - setWeight: 25
        - pause: {duration: 30s}
        
