apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - image: codefreshjesse/express-microservice2:702b2e189d6b2a24e0019eeb6651469f8eb54bac
        #- image: 336151728602.dkr.ecr.us-east-1.amazonaws.com/salesdemocf/express-microservice:03a3fc0 # 99d94a2 # d3cb357
          name: express
          ports:
            - containerPort: 3000
  minReadySeconds: 30
  strategy:
    canary:
      steps:
        - setWeight: 25
        - setWeight: 25
        - pause: {}
