apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-prod
  # namespace: csdp01-us-east-2  # All app resources live in the argocd namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: express
spec:
  destination:
    namespace: express-prod
    name: in-cluster
  project: express
  source:
    repoURL: https://github.com/codefresh-contrib/example-multiservice-deploy2.git
    targetRevision: main
    path: express/prod
