apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multiservice-test
  namespace: captest  # All app resources live in the argocd namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: multiservice
spec:
  destination:
    namespace: multiservice-test
    name: in-cluster
  project: example-multiservice
  source:
    repoURL: https://github.com/codefresh-contrib/example-multiservice-deploy2.git
    targetRevision: main
    path: test
    helm:
      parameters:
        - name: buildID
          value: argocd
      valueFiles:
        - values.yaml