apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multiservice-stage
  namespace: argo-cd  # All app resources live in the argocd namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: multiservice-stage
    name: in-cluster
  project: example-multiservice
  source:
    repoURL: https://github.com/codefresh-contrib/example-multiservice-deploy2.git
    targetRevision: main
    path: stage
    helm:
      parameters:
        - name: buildID
          value: argocd
      valueFiles:
        - values.yaml