kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: background-analysis
spec:
  metrics:
    - name: pass-7
      count: 7
      interval: 5s
      failureLimit: 1
      provider:
        job:
          spec:
            template:
              spec:
                containers:
                  - name: pass-7-container
                    image: alpine:3.8
                    command: [sh, -c]
                    args: [exit 0]
                restartPolicy: Never
            backoffLimit: 0
    - name: random-fail
      count: 1
      interval: 5s
      failureLimit: 1
      provider:
        job:
          spec:
            template:
              spec:
                containers:
                  - name: sleep-fail
                    image: alpine:3.8
                    command: [sh, -c]
                    args: [FLIP=$(($(($RANDOM%10))%2)) && exit $FLIP]
                restartPolicy: Never
            backoffLimit: 0
