kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: experiment-analysis
spec:
  metrics:
    - name: random-fail-experiment
      count: 1
      interval: 5s
      failureLimit: 1
      provider:
        job:
          spec:
            template:
              spec:
                containers:
                  - name: fail-experiment
                    image: alpine:3.8
                    command: [sh, -c]
                    args: [FLIP=$(($(($RANDOM%10))%2)) && exit $FLIP]
                restartPolicy: Never
            backoffLimit: 0
